[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--version" # prevent Netlify npm install
[build]
  publish = "docs/.vitepress/dist"
  command = "npm i -g --force corepack && corepack enable && npx pnpm i --store=node_modules/.pnpm-store --frozen-lockfile && npm run docs:build"
  ignore = "./scripts/docs-check.sh"
