name: Release

permissions:
  contents: write
  id-token: write

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4

      - name: Set node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: current
          cache: pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Prepare for release
        run: |
          pnpm run format
          pnpm run lint
          pnpm run type-check
          pnpm run clean
          pnpm run build
          pnpm run publint

      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
        id: version_to_release
        with:
          result-encoding: string
          script: |
            const fs = require('fs');
            const packageJson = JSON.parse(fs.readFileSync('./packages/vite-plugin-checker/package.json', 'utf8'));
            return packageJson.version;

      - name: Publish to NPM
        run: |
          cp README.md packages/vite-plugin-checker/README.md
          git tag vite-plugin-checker@${{ steps.version_to_release.outputs.result }}
          git push origin vite-plugin-checker@${{ steps.version_to_release.outputs.result }}
          pnpm -r publish --no-git-checks

      - name: GitHub release
        run: pnpx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
